INSERT INTO categories (name, description) VALUES
    ('Fresco', 'A mural painting technique where pigments are applied on freshly laid lime plaster. Famous Examples: Michelangelo’s The Sistine Chapel Ceiling. Characteristics: Long-lasting and vibrant colors, Requires quick application before the plaster dries'),
    ('Tempera', 'A fast-drying painting method using pigments mixed with egg yolk or another binder. Famous Examples: The Birth of Venus by Sandro Botticelli. Characteristics: Smooth, matte finish, Fine details and crisp lines, Used extensively before oil painting gained popularity'),
    ('Oil Painting', 'Pigments are mixed with oil (linseed, walnut, or poppy seed), allowing for rich color blending. Famous Examples: Mona Lisa by Leonardo da Vinci, The Night Watch by Rembrandt. Characteristics: Slow drying time, enabling smooth blending, Deep, rich colors with strong contrast, Layering (glazing) for depth and luminosity'),
    ('Baroque', 'Period: 17th century. Famous Artists: Caravaggio, Peter Paul Rubens, Rembrandt. Characteristics: Dramatic lighting (chiaroscuro), Emotional intensity and movement, Rich, deep colors and strong contrast'),
    ('Rococo', 'Period: 18th century. Famous Artists: François Boucher, Jean-Honoré Fragonard. Characteristics: Soft, pastel colors, Light, playful themes (romance, mythology, leisure), Delicate brushwork and intricate details'),
    ('Neoclassicism', 'Period: Late 18th to early 19th century. Famous Artists: Jacques-Louis David, Jean-Auguste-Dominique Ingres. Characteristics: Inspired by ancient Greek and Roman art, Sharp lines, balanced compositions, Focus on heroic, moralistic themes'),
    ('Romanticism', 'Period: Late 18th to mid-19th century. Famous Artists: Francisco Goya, Eugène Delacroix, J.M.W. Turner. Characteristics: Strong emotions, drama, and imagination, Nature as a powerful force, Expressive brushwork and intense colors'),
    ('Realism', 'Period: Mid-19th century. Famous Artists: Gustave Courbet, Jean-François Millet. Characteristics: Focus on everyday life and ordinary people, Avoids idealization and exaggeration, Precise, detailed brushwork'),
    ('Academic Art', 'Period: 17th–19th century. Famous Artists: William-Adolphe Bouguereau, Alexandre Cabanel. Characteristics: Highly polished and detailed, Idealized beauty and historical themes, Strong focus on anatomy and composition');
